apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: dapr-demo-api
  namespace: default
spec:
  secrets:
    scopes:
      - storeName: localsecretstore
        defaultAccess: deny
        allowedSecrets: ['port']
